//
// Created by loust on 07/07/2023.
//

#ifndef WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_INCLUDE_OBOEAUDIORECORDER_H_
#define WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_INCLUDE_OBOEAUDIORECORDER_H_

#endif //WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_INCLUDE_OBOEAUDIORECORDER_H_
